__author__ = 'Ronald Zhao'
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:123456@127.0.0.1:3306/blog'
SQLALCHEMY_TRACK_MODIFICATIONS = True
# 下面是RECAPCHA的配置，目前无响应。
# RECAPTCHA_PUBLIC_KEY = '6Lc6ZmEUAAAAAAn8FKldY6VUs_XORUspulsyyD10'
# RECAPTCHA_PRIVATE_KEY = '6Lc6ZmEUAAAAAGJS9PWqgf8AYRMrVC1oscygt7bj'
